name: Record M3U 1 Minute

on:
  workflow_dispatch:

jobs:
  record:
    runs-on: ubuntu-latest

    steps:
      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Record 1 minute
        run: ffmpeg -loglevel error -y -i https://live.fptplay53.net/fnxch2/vtvcantho_abr.smil/chunklist_b4200000.m3u8 -map 0 -c copy -t 60 output.ts

      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: video-1p
          path: output.ts
