name: Record 5 Minutes

on:
  workflow_dispatch:

jobs:
  record:
    runs-on: ubuntu-latest

    steps:
      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Record 5 minutes
        run: |
          ffmpeg -loglevel error -y \
          -i https://live.fptplay53.net/live/media/VTV_can_tho/live_hls_avc/index.m3u8 \
          -map 0 \
          -c copy \
          -fflags +genpts \
          -avoid_negative_ts make_zero \
          -t 300 \
          output.ts

      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: video-5p
          path: output.ts
